package net.osgiliath.agentsdk.agent.executor.internal;

import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.data.message.UserMessage;
import net.osgiliath.agentsdk.agent.executor.internal.skillenrichment.AgentSkillsInstructionEnricher;
import net.osgiliath.agentsdk.agent.parser.Agent;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Orchestrates eager skill context injection into the tool-calling loop.
 * <p>
 * Decides when to inject skill payload into the message stream based on the AI
 * message content, and delegates parsing and rendering to
 * {@link AgentSkillsInstructionEnricher}.
 */
@Component
public class SkillInformationOrchestrator {

    private final AgentSkillsInstructionEnricher enricher;

    public SkillInformationOrchestrator(AgentSkillsInstructionEnricher enricher) {
        this.enricher = Objects.requireNonNull(enricher, "enricher must not be null");
    }

    /**
     * Returns the protocol instruction that should be prepended to the message list
     * so the agent knows how to signal eager skill context requests.
     *
     * @param agent the current agent
     * @return the protocol instruction string, or blank if the agent has no skills
     */
    public String protocolInstruction(Agent agent) {
        Objects.requireNonNull(agent, "agent must not be null");
        return enricher.protocolInstruction(agent);
    }

    /**
     * Detects whether the AI message contains an eager-skill-context request and, if
     * so, injects the appropriate payload (or a deduplication notice) into
     * {@code messages}.
     *
     * @param aiMessage                  the last AI message produced by the model
     * @param messages                   mutable message list to inject into
     * @param servedEagerContextRequests set of already-served request signatures
     *                                   (bounded, mutable)
     * @param agent                      the current agent
     * @param toolCallHistoryLimit       bound applied when recording the signature
     * @return {@code true} if an injection was performed and the loop should
     * continue without terminating; {@code false} if no eager context was requested
     */
    public boolean injectEagerSkillsIfAsked(AiMessage aiMessage,
                                            List<ChatMessage> messages,
                                            LinkedHashSet<String> servedEagerContextRequests,
                                            Agent agent,
                                            int toolCallHistoryLimit) {
        Objects.requireNonNull(aiMessage, "aiMessage must not be null");
        Objects.requireNonNull(messages, "messages must not be null");
        Objects.requireNonNull(servedEagerContextRequests, "servedEagerContextRequests must not be null");
        Objects.requireNonNull(agent, "agent must not be null");
        if (toolCallHistoryLimit <= 0) {
            throw new IllegalArgumentException("toolCallHistoryLimit must be greater than 0");
        }

        Optional<AgentSkillsInstructionEnricher.EagerSkillContextRequest> maybeRequest =
                enricher.extractRequest(aiMessage);
        if (maybeRequest.isEmpty()) {
            return false;
        }

        String signature = enricher.requestSignature(maybeRequest.get());
        if (servedEagerContextRequests.contains(signature)) {
            messages.add(UserMessage.from(
                    "Eager skill context for this JSON request was already provided in this pass. "
                            + "Use it and continue with concrete tool calls."));
            return true;
        }

        String payload = enricher.renderPayload(agent, maybeRequest.get());
        messages.add(UserMessage.from(
                "Eager skill context payload (auto-generated by executor):\n"
                        + payload
                        + "\n\nUse this payload immediately and continue with concrete tool calls."));
        putBoundedSet(servedEagerContextRequests, signature, toolCallHistoryLimit);
        return true;
    }

    private <V> void putBoundedSet(LinkedHashSet<V> target, V value, int limit) {
        if (!target.contains(value) && target.size() >= limit) {
            Iterator<V> iterator = target.iterator();
            if (iterator.hasNext()) {
                iterator.next();
                iterator.remove();
            }
        }
        target.add(value);
    }
}

